spring:
  data:
    mongodb:
      authentication-database: none
      database: testdb
      port: 27017
      host: localhost
mongock:
  runner-type: "InitializingBean" 
  change-logs-scan-package:
  - ru.otus.spring.springdata.changelogs