spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/work


mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
  - ru.otus.spring.batch.changelogs